name: Actualizar M3U8 Telefe

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-m3u8:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Ejecutar script de actualización
        run: node update_telefe.js

      - name: Subir cambios a GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add telefe.m3u8
          git commit -m "Auto-update telefe.m3u8 [skip ci]" || exit 0
          git push
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add telefe.m3u8
          git commit -m "Auto-update telefe.m3u8 [skip ci]" || exit 0
          git push
